
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlzwrlgtjshcjfxfchyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sendybGd0anNoY2pmeGZjaHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTQ0OTksImV4cCI6MjA2MzM3MDQ5OX0.-HJhOWKhgGzH_h8bKSUJ6-p9QJ8ZUecXB9qTqMyYmKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'X-Application-Context': 'daveops-portfolio'
    }
  }
});

// Application-specific table prefixes for data isolation
export const TABLE_PREFIXES = {
  DAVEOPS: 'daveops_',
  SHARED: '' // For shared tables like profiles
} as const;

// Helper function to get table name with proper prefix
export const getTableName = (tableName: string, prefix: keyof typeof TABLE_PREFIXES = 'DAVEOPS') => {
  return `${TABLE_PREFIXES[prefix]}${tableName}`;
};
