
name: Build and Deploy to Production

on:
  repository_dispatch:
    types: [deploy-to-prod]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout stage repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies and build
      env:
        BUILD_COMMAND: ${{ github.event.client_payload.build_command }}
      run: |
        echo "=== Starting build process ==="
        npm cache clean --force
        rm -f package-lock.json
        npm install
        
        # Run the build command (default to npm run build)
        if [ -n "$BUILD_COMMAND" ]; then
          echo "Running custom build command: $BUILD_COMMAND"
          $BUILD_COMMAND
        else
          echo "Running default build command: npm run build"
          npm run build
        fi
        
        # Verify build output exists
        if [ ! -d "dist" ] && [ ! -d "build" ]; then
          echo "❌ Error: No build output found (looking for 'dist' or 'build' directory)"
          exit 1
        fi
        
        echo "✓ Build completed successfully"
        
    - name: Configure Git
      run: |
        git config --global user.name 'Production Deploy Bot'
        git config --global user.email 'prod-deploy@dave-ops.net'
        
    - name: Deploy built files to production repository
      env:
        PORTFOLIO_TOKEN: ${{ secrets.PORTFOLIO_TOKEN }}
        TARGET_REPO: ${{ github.event.client_payload.target_repo }}
        PROJECT_NAME: ${{ github.event.client_payload.project_name }}
      run: |
        echo "=== Starting production deployment ==="
        
        # Determine build output directory
        if [ -d "dist" ]; then
          BUILD_DIR="dist"
        elif [ -d "build" ]; then
          BUILD_DIR="build"
        else
          echo "❌ Error: No build directory found"
          exit 1
        fi
        
        echo "✓ Using build directory: $BUILD_DIR"
        
        # Clone or initialize the production repository
        if git clone https://x-access-token:${PORTFOLIO_TOKEN}@github.com/${TARGET_REPO}.git prod-repo 2>/dev/null; then
          echo "✓ Cloned existing production repository"
          cd prod-repo
          # Remove existing content except .git and .github
          find . -maxdepth 1 ! -name '.git' ! -name '.github' ! -name '.' ! -name '..' -exec rm -rf {} + 2>/dev/null || true
          echo "✓ Cleaned existing production repository"
        else
          echo "✓ Creating new production repository"
          mkdir prod-repo
          cd prod-repo
          git init
          git remote add origin https://x-access-token:${PORTFOLIO_TOKEN}@github.com/${TARGET_REPO}.git
          git checkout -b main
        fi
        
        # Copy built files from build directory to production root using tar
        cd ../$BUILD_DIR
        tar -cf - . | (cd ../prod-repo && tar -xf -)
        cd ../prod-repo
        echo "✓ Copied build files to production repository"
        
        # Add GitHub Pages workflow if it doesn't exist
        if [ ! -f ".github/workflows/github-pages.yml" ]; then
          mkdir -p .github/workflows
          cat > .github/workflows/github-pages.yml << 'EOF'
